# Time between town entity spawn/despawn check
town_verification_timer_s: 3

# Time between new quest spawns
quest_spawn_delay_s: 60

# A town can level up in a number of ways
# - Completing a quest with the town as the origin (10xp for delivery)
# - Completing a quest with the town as the destination (0.2x hand in)
#
# xp is cumulative, if level 1 requires 100 xp and level 2 requires 200 xp, it will reach level 2
# at a total of 300 xp
levels:
  - level: 0
    xp_threshold: 0
    quest_reward_multiplier: 0.75
    max_simultaneous_quests: 1

  - level: 1
    xp_threshold: 100
    quest_reward_multiplier: 1.0
    max_simultaneous_quests: 3

  - level: 2
    xp_threshold: 1000
    quest_requirements_multiplier: 1.25
    quest_reward_multiplier: 1.5
    max_simultaneous_quests: 3

  - level: 3
    xp_threshold: 5000
    quest_requirements_multiplier: 1.5
    quest_reward_multiplier: 2.0
    max_simultaneous_quests: 4