internal_name: default
body:
  x: 0
  y: 0
  z: 0
head:
  x: 0
  y: 0
  z: 0
left_arm:
  x: 0
  y: 0
  z: 0
left_leg:
  x: 0
  y: 0
  z: 0
right_arm:
  x: 0
  y: 0
  z: 0
right_leg:
  x: 0
  y: 0
  z: 0